// src/modules/tag/components/TagList.tsx
// src/modules/tag/components/TagList.tsx

import React from 'react';
import { Box, Flex, Text } from 'gestalt';
import { TagChip } from './TagChip';
import type { TagResponse } from '../types/tag.types';

interface TagListProps {
  tags: (TagResponse | string)[];
  size?: 'sm' | 'md' | 'lg';
  onClick?: (tag: string) => void;
  selectedTags?: string[];
  onTagSelect?: (tag: string) => void;
  onTagDeselect?: (tag: string) => void;
  removable?: boolean;
  onRemove?: (tag: string) => void;
  emptyMessage?: string;
  wrap?: boolean;
  gap?: 1 | 2 | 3 | 4;
  navigateOnClick?: boolean;
  maxVisible?: number;
}

export const TagList: React.FC<TagListProps> = ({
  tags,
  size = 'md',
  onClick,
  selectedTags = [],
  onTagSelect,
  onTagDeselect,
  removable = false,
  onRemove,
  emptyMessage,
  wrap = true,
  gap = 2,
  navigateOnClick = false,
  maxVisible,
}) => {
  if (tags.length === 0 && emptyMessage) {
    return (
      <Box paddingY={2}>
        <Text color="subtle" size="200">
          {emptyMessage}
        </Text>
      </Box>
    );
  }

  const visibleTags = maxVisible ? tags.slice(0, maxVisible) : tags;
  const hiddenCount = maxVisible ? Math.max(0, tags.length - maxVisible) : 0;

  const handleTagClick = (tagName: string) => {
    if (onClick) {
      onClick(tagName);
      return;
    }

    const isSelected = selectedTags.includes(tagName);
    if (isSelected && onTagDeselect) {
      onTagDeselect(tagName);
    } else if (!isSelected && onTagSelect) {
      onTagSelect(tagName);
    }
  };

  return (
    <Flex wrap={wrap} gap={gap}>
      {visibleTags.map((tag) => {
        const tagName = typeof tag === 'string' ? tag : tag.name;
        const isSelected = selectedTags.includes(tagName);

        return (
          <TagChip
            key={tagName}
            tag={tag}
            size={size}
            selected={isSelected}
            onClick={onClick || onTagSelect || onTagDeselect ? handleTagClick : undefined}
            removable={removable}
            onRemove={onRemove}
            navigateOnClick={navigateOnClick && !onClick}
          />
        );
      })}
      
      {hiddenCount > 0 && (
        <Box
          paddingX={3}
          paddingY={2}
          rounding="pill"
          color="secondary"
        >
          <Text size="200" color="subtle">
            +{hiddenCount} more
          </Text>
        </Box>
      )}
    </Flex>
  );
};

export default TagList;

// src/components/ui/TagList.vue
<script setup lang="ts">
import { computed } from 'vue'
import TagBadge from './TagBadge.vue'

export interface Tag {
  id: string | number
  name: string
  color?: string
}

export interface TagListProps {
  tags: Tag[]
  selectedTags?: (string | number)[]
  selectable?: boolean
  removable?: boolean
  maxVisible?: number
  size?: 'sm' | 'md' | 'lg'
  wrap?: boolean
}

const props = withDefaults(defineProps<TagListProps>(), {
  selectedTags: () => [],
  selectable: false,
  removable: false,
  maxVisible: 0,
  size: 'md',
  wrap: true,
})

const emit = defineEmits<{
  (e: 'select', tag: Tag): void
  (e: 'remove', tag: Tag): void
}>()

const visibleTags = computed(() => {
  if (props.maxVisible > 0) {
    return props.tags.slice(0, props.maxVisible)
  }
  return props.tags
})

const hiddenTagsCount = computed(() => {
  if (props.maxVisible > 0 && props.tags.length > props.maxVisible) {
    return props.tags.length - props.maxVisible
  }
  return 0
})

const isSelected = (tagId: string | number) => {
  return props.selectedTags.includes(tagId)
}

const handleSelect = (tag: Tag) => {
  emit('select', tag)
}

const handleRemove = (tag: Tag) => {
  emit('remove', tag)
}
</script>

<template>
  <div :class="['flex items-center gap-2', wrap ? 'flex-wrap' : 'flex-nowrap overflow-x-auto']">
    <TagBadge
      v-for="tag in visibleTags"
      :key="tag.id"
      :label="tag.name"
      :color="tag.color"
      :selected="isSelected(tag.id)"
      :removable="removable"
      :clickable="selectable"
      :size="size"
      @click="handleSelect(tag)"
      @remove="handleRemove(tag)"
    />

    <span
      v-if="hiddenTagsCount > 0"
      :class="[
        'inline-flex items-center rounded-full font-medium bg-gray-200 text-gray-700',
        size === 'sm'
          ? 'text-xs px-2 py-1'
          : size === 'md'
            ? 'text-sm px-3 py-2'
            : 'text-base px-4 py-2',
      ]"
    >
      +{{ hiddenTagsCount }}
    </span>
  </div>
</template>
